### ISSUE TITLE
provide install arguments for canisters

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/motoko-dev-server#48]
it seems like there is no way to provide install arguments for canisters, can this  be added?

**Comment by rvanasa** [comment]
It's now possible to pass `--argument` flags in `mo-dev` 0.11.0!

This is currently subject to the same limitations as directly running `dfx deploy <canister> --argument <arg>`, so it might be necessary to do a `dfx start --clean` to reset the original install args if needed. Let me know if you run into any issues with this, and I could see if there's a way to detect and fix these corner cases in the dev server logic.

**Comment by letmejustputthishere** [comment]
Awesome, thanks for the quick response!
